### ISSUE TITLE
Google Safe Browsing

### ISSUE THREAD

**Issue by gary00k** [graysuit/grayfish#11]
Hello, how about google safe browsing? I mean, this red alert in chrome warning about phishing page. Is it undetectable?

**Comment by graysuit** [comment]
there's many reasons:
- site is insecure (http:// having invalid certificate)
- domain is malicious e.g *.000webhost.com, *.freeweb.pk

Share link or web hosting which you are trying.

**Comment by gary00k** [comment]
I have SSL certificate and own domain like mfacebook.*
I didn't try grayfish yet, only asking if can it bypass google safe browsing? I think google analyzes color scheme and/or something else.

**Comment by gary00k** [comment]
EDIT:
Ok, i tried LitePhish. Fake site is immediately blocked by Google Safe Browsing.
Chrome is probably the most used browser, and other popular browsers like FireFox use GSB too. So, it's a little bit useless if user get notified with big red alert every time he enter my site :/ Is there any way to bypass it?

**Comment by graysuit** [comment]
Social media apps are used more than chrome.
And that apps are just like web browsers, but having no anti phish mechanism.

It doesn't matter what subdomain you use. Main thing is domain.
Are you using free domain ? Which hosting are you using ?
Does google block that link even when having no phishing page ?

**Comment by gary00k** [comment]
Well, at this moment I found really simple solution for bypassing GSB ;)
Thanks for your help.

**Comment by daniesy** [comment]
@gary00k can you please share your solution with me?

**Comment by graysuit** [comment]
> Social media apps are used more than chrome. And that apps are just like web browsers, but having no anti phish mechanism.
> 
> It doesn't matter what subdomain you use. Main thing is domain. Are you using free domain ? Which hosting are you using ? Does google block that link even when having no phishing page ?

@daniesy that was idea he found. 
But do note some apps visit link, check for phishing and block it, like facebook does.

**Comment by gary00k** [comment]
No. In my experience this is bypassing everything, except human ;)
