### ISSUE TITLE
congratulations and please add google and microsoft

### ISSUE THREAD

**Issue by Mrcosta20** [graysuit/grayfish#2]
great project congratulations it seems very educational to me. I would like you to add google and microsoft and fix the netflix code, I used your code for a while and it seems very good to me. keep it up with your projects

**Comment by graysuit** [comment]
Glad to hear that :)
I will add Google + Microsoft template soon.

What is problem with Netflix code ?
Tell me so that I may fix it.

**Comment by Mrcosta20** [comment]
netflix's mistake is that the background looks very distorted not so real but I know you will fix it
and also I follow you on youtube happy night

**Comment by graysuit** [comment]
Yes its background was distorted,
I fixed it,
See whether it is working for you now ?

**Comment by Mrcosta20** [comment]
Ok friend, thank you very much

**Comment by graysuit** [comment]
Welcome bro
