### ISSUE TITLE
dropbox

### ISSUE THREAD

**Issue by lordcharlx** [graysuit/grayfish#3]
please add dropbox page

**Comment by graysuit** [comment]
I will add soon

**Comment by lordcharlx** [comment]
@graysuit  awesome ................i cant wait im also willing to support this project

**Comment by graysuit** [comment]
Making issues and telling developers about project is also an type of support,
Which fix bugs and release new features,
Thanks for your kindness.

We will make this page under 1 week.

**Comment by lordcharlx** [comment]
@graysuit where is the dropbox page you promised its pass one week now

**Comment by graysuit** [comment]
I am finalizing,
Be prepared,
Today it will be launched.

**Comment by lordcharlx** [comment]
@graysuit  awesome ...will be waiting

**Comment by graysuit** [comment]
Done ! Added Dropbox,
Sorry for one day late,
I remain toughly busy.

View and tell me is it working and fine ?

**Comment by lordcharlx** [comment]
![Screenshot at 2020-06-03 13-46-14](https://user-images.githubusercontent.com/5570136/83638489-bf38bc80-a598-11ea-9834-cf1e78fda3d9.png)
broken image

**Comment by lordcharlx** [comment]
thanks for the great work

**Comment by lordcharlx** [comment]
![Screenshot at 2020-06-03 14-36-38](https://user-images.githubusercontent.com/5570136/83643260-56a10e00-a59f-11ea-86f9-71e33e0d8ef7.png)
see the legit site

**Comment by graysuit** [comment]
Yeah I know,
Just names of images were not correctly set,
Wait untill I fix,

This was working fine in localhost,
May be it has some issues in hosting.
wait

**Comment by lordcharlx** [comment]
working fine in lamp just the broken image

**Comment by graysuit** [comment]
There was an mistake,
I used the folder name Images
Whereas I called it using images
So that's why images from images folder doesn't seen on page,

Fix fixing it in 2 min.

**Comment by graysuit** [comment]
It is fixed,
Download and see again now.

**Comment by lordcharlx** [comment]
awesome two thumbs up

**Comment by lordcharlx** [comment]
![WhatsApp Image 2020-06-03 at 14 42 27](https://user-images.githubusercontent.com/5570136/83651043-90c2dd80-a5a8-11ea-8261-239aed4a7c7e.jpeg)
so sorry to bug you somechrome have issues rendering it

**Comment by graysuit** [comment]
I tried and tested on chrome ,it works fine,
Try to re download it or try link on any other browser,
May be browser has saved the old state,

Or even problem not solved then,
Prepare yourself for team viewer support if you want,
I want to see the problem.

**Comment by graysuit** [comment]
here you can see,
it is working fine,

**Note that don't put any sensitive data,**
Following is fish link.

http://ytry7wetduagj.000webhostapp.com/Gray%20fish/sites/dropbox.php

**Comment by lordcharlx** [comment]
> ![Screenshot at 2020-06-03 14-36-38](https://user-images.githubusercontent.com/5570136/83643260-56a10e00-a59f-11ea-86f9-71e33e0d8ef7.png)
> see the legit site

awesome job you are doing but please refer to the legit site as there is huge difference

**Comment by graysuit** [comment]
Dropbox is an big site,
It shows every person and every device and every browser a different view,
Phishing page can't be 100% clone of real site nor it can be a real site,

And also its not too much different from original,
I noted all this in my phishing experience,
Not just language, see also the difference of checkbox,image in different browsers.

https://www.dropbox.com/fr/login
https://www.dropbox.com/es_ES/login
https://www.dropbox.com/es/login
https://www.dropbox.com/de/login
https://www.dropbox.com/da_DK/login


Thanks

**Comment by graysuit** [comment]
Should I close this issue now ?

**Comment by lordcharlx** [comment]
yea thanks for the surport issue fixed

**Comment by graysuit** [comment]
Great
