### ISSUE TITLE
Fork and maintain

### ISSUE THREAD

**Issue by graysuit** [graysuit/grayfish#4]
This was my first php project and also I am sad to not maintain it further more due to lack of time.
But I can put it on the community. They can make it more better.
I will encourage people to **fork this project and start modifying and maintain it.**
Thanks.

**Comment by graysuit** [comment]
@darkmidus It may interests you.

**Comment by swagkarna** [comment]
> @darkmidus and @swagkarna It may interests you.
> You can clear any doubts here.
> Anyone can fork and become successor.

sure bro

**Comment by graysuit** [comment]
@swagkarna 
I am happy to transfer maintenance to a person who is well known in phish coding.
You will receive an email with invitation from github.
And backup of grayfish can be found at github.com/graysuit/grayfish_bak

**Comment by graysuit** [comment]
I will have little time. So will be going to maintain it. Thanks
